title: The Story of Brickmaking
description: >- # this means to ignore newlines until "baseurl:"
  The Story of Brickmaking in Pollagh, County Offaly - a book by Caitriona Devery
url: "story-of-brickmaking"

theme: minima